### ISSUE TITLE
DAQmx configuration for Mac OS X

### ISSUE THREAD

**Issue by thoo** [clade/PyDAQmx#19]
Hi ,
How can I update the DaqmxConfig.py for mac os x? I know the location of "`NIDAQmxBase.h`" file. 

`/Applications/National Instruments/NI-DAQmx Base/includes/NIDAQmxBase.h`

When I run `find_library('nidaqmxbase')` , I got `'/Library/Frameworks/nidaqmxbase.framework/nidaqmxbase'`. Thanks,

**Comment by clade** [comment]
Thanks to the informations that you send me, I have updated the 
DAQmxConfig.py file. Can you test it ?

**Comment by thoo** [comment]
Thanks. It seems working now. I just need to find the right NI-DAQ driver which supports 64 bit and also my USB card.
