### ISSUE TITLE
64 Bit Python?

### ISSUE THREAD

**Issue by mousemeat** [clade/PyDAQmx#28]
Question: Is PyDAQmx compatible with 64-bit python (specifically 3.5)?

**Comment by clade** [comment]
It should be. If you have any problem, please send a message (with the version of windows and NI DAQmx installed).

**Comment by mousemeat** [comment]
Thank you.  I will let you know if I reach a definitive conclusion.

Warren

**Comment by mousemeat** [comment]
I can confirm that PyDAQmx works perfectly in 64-bit Python 3 (Anaconda 4.0.0 Distribution).  NI version 15.3.0f0.  

Great stuff.
