### ISSUE TITLE
Named Tasks

### ISSUE THREAD

**Issue by edbarnard** [clade/PyDAQmx#42]
Hi I've been wanting to make tasks with a name so that its easier to debug. The default `Task` does not include an option for a name, which is an argument for `DAQmxCreateTask`. 

I've included a class that wraps `Task` that allows for the name. I think an optional name argument in `Task.__init__` would be a helpful addition, so that wrapping it like this is no longer necessary.

Thanks!
-Ed 

```python
class NamedTask(mx.Task):
    ''' replaces __init__ with one that accepts a name for the task, otherwise identical to PyDaqmx task
        override PyDAQmx definition, which does not support named tasks
        no special chars in names, space OK
    '''
    def __init__(self, name= b''):
        self.taskHandle = mx.TaskHandle(0)
        mx.DAQmxCreateTask(name, mx.byref(self.taskHandle))
```

**Comment by clade** [comment]
Thanks for you your comment. The optional argument has been included in 7b4589efa5701074d29883b4e8c5c09d1a2dc57a and 9044ffa476e2f5a3b54f1bb45a8c9a46bcc4d2fd
